from typing import Protocol

from src.modules.auth.domain.models import AuthUser
from src.modules.usuarios.domain.models import UserModel, DireccionModel, DeviceToken

class UserPort(Protocol):
    def get_all(self) -> list[UserModel]: ...

    def get_by_id(self, usuario_id: str) -> UserModel | None: ...

    def get_by_email(self, email: str) -> UserModel | None: ...

    def update(self, usuario_id: str, user: UserModel) -> UserModel: ...

    def delete(self, usuario_id: str) -> None: ...

    def anonymize_and_soft_delete(self, usuario_id: str) -> None: ...

    def create_admin(self, user: AuthUser) -> UserModel: ...

    def get_all_admins(self) -> list[UserModel]: ...

class DireccionPort(Protocol):
    def get_direcciones_by_usuario_id(self, usuario_id: str) -> list[DireccionModel]: ...

    def get_direccion_by_id(self, direccion_id: int, usuario_id: str ) -> DireccionModel | None: ...

    def create_direccion(self, direccion: DireccionModel) -> DireccionModel: ...

    def update_direccion(self, direccion_id: int, direccion: DireccionModel, usuario_id: str) -> DireccionModel | None: ...

    def delete_direccion(self, direccion_id: int, usuario_id: str) -> None: ...

    def set_primary(self, direccion_id: int, usuario_id: str) -> None: ...


class DeviceTokenPort(Protocol):

    def save(self, user_id: str, token: str) -> None:
        ...

    def get_by_user(self, user_id: int) -> list[DeviceToken]:
        ...

    def get_all(self) -> list[DeviceToken]:
        ...

    def delete(self, token: str) -> None:
        ...