from typing import Protocol, List, Optional
from src.modules.usuarios.domain.models import UserModel

class UserPort(Protocol):

    def get_all(self) -> List[UserModel]: ...

    def get_by_id(self, usuario_id: str) -> Optional[UserModel]: ...

    def get_by_email(self, email: str) -> Optional[UserModel]: ...

    def update(self, usuario_id: str, user: UserModel) -> UserModel: ...

    def delete(self, usuario_id: str) -> None: ...

    def anonymize_and_soft_delete(self, usuario_id: str) -> None: ...
