from src.modules.usuarios.domain.models import UserModel, DireccionModel
from typing import Protocol, List, Optional

class UserPort(Protocol):

    def get_all(self) -> List[UserModel]: ...

    def get_by_id(self, usuario_id: str) -> Optional[UserModel]: ...

    def get_by_email(self, email: str) -> Optional[UserModel]: ...

    def update(self, usuario_id: str, user: UserModel) -> UserModel: ...

    def delete(self, usuario_id: str) -> None: ...

    def anonymize_and_soft_delete(self, usuario_id: str) -> None: ...

class DireccionPort(Protocol):
    def get_direcciones_by_usuario_id(self, usuario_id: str) -> List[DireccionModel]: ...

    def get_direccion_by_id(self, direccion_id: int, usuario_id: str ) -> Optional[DireccionModel]: ...

    def create_direccion(self, direccion: DireccionModel) -> DireccionModel: ...

    def update_direccion(self, direccion_id: int, direccion: DireccionModel, usuario_id: str) -> Optional[DireccionModel]: ...

    def delete_direccion(self, direccion_id: int, usuario_id: str) -> None: ...

    def set_primary(self, direccion_id: int, usuario_id: str) -> None: ...