from typing import Protocol
from ..models import CategoriaModel

class CategoriaPort(Protocol):
    async def get_by_id(self, categoria_id: int) -> CategoriaModel | None: ...

    async def get_all(self) -> list[CategoriaModel]: ...

    async def get_all_by_seccion(self, seccion: int) -> list[CategoriaModel]: ...

    async def create(self, categoria: CategoriaModel) -> CategoriaModel: ...

    async def update(self, categoria_id: int, categoria: CategoriaModel) -> CategoriaModel | None: ...

    async def delete(self, categoria_id: int) -> None: ...
