from typing import Protocol
from ..models import CategoriaModel

class CategoriaPort(Protocol):
    def get_by_id(self, categoria_id: int) -> CategoriaModel | None: ...

    def get_all(self) -> list[CategoriaModel]: ...

    def get_all_by_seccion(self, seccion: int) -> list[CategoriaModel]: ...

    def create(self, categoria: CategoriaModel) -> CategoriaModel: ...

    def update(self, categoria_id: int, categoria: CategoriaModel) -> CategoriaModel | None: ...

    def delete(self, categoria_id: int) -> None: ...