from typing import Protocol

from src.modules.catalogo.domain.models import ColorModel, ProductoColorModel


class ColorPort(Protocol):
    def get_all(self) -> list[ColorModel]: ...

    def get_by_id(self, color_id: int) -> ColorModel | None: ...

    def create(self, model: ColorModel) -> ColorModel: ...

    def update(self, color_id: int, model: ColorModel) -> ColorModel | None: ...

    def delete(self, color_id: int) -> None: ...


class ProductoColorPort(Protocol):
    def get_all_by_producto(self, p_id: str) -> list[ColorModel]: ...

    def get_by_id(self, p_color_id: int) -> ProductoColorModel: ...

    def assign_to_producto(self, p_color: ProductoColorModel) -> ProductoColorModel: ...

    def remove_from_producto(self, producto_id: str,color_id: int) -> None: ...
