from typing import Protocol
from ..models import ImagenModel, ProductoImagenModel

class ImageStoragePort(Protocol):
    def upload(self, content: bytes, path: str) -> str: ...

    def delete(self, path: str) -> None: ...

class ImagePort(Protocol):
    async def create(self, imagen: ImagenModel) -> ImagenModel: ...

    async def get_by_id(self, imagen_id: int) -> ImagenModel | None: ...

    async def delete(self, imagen_id: int) -> None: ...

class ProductImagePort(Protocol):
    async def create(self, relation: ProductoImagenModel) -> ProductoImagenModel: ...

    async def delete(self, producto_id: str, imagen_id: int) -> None: ...

    async def get_by_producto(self, producto_id: str) -> list[ProductoImagenModel]: ...

    async def delete_by_producto(self, producto_id: str) -> None: ...
