from typing import Protocol
from ..models import ProductoModel

class ProductoPort(Protocol):
    async def get_by_id(self, producto_id: str) -> ProductoModel | None: ...

    async def get_all(self) -> list[ProductoModel]: ...

    async def get_by_categoria(self, categoria_id: int) -> list[ProductoModel]: ...

    async def create_producto(self, producto: ProductoModel) -> ProductoModel: ...

    async def update_producto(self, producto_id: str, producto: ProductoModel) -> ProductoModel: ...

    async def delete_producto(self, producto_id: str) -> None: ...
