from typing import Protocol
from ..models import SeccionModel

class SeccionPort(Protocol):
    def get_seccion_by_id(self, seccion_id: int) -> SeccionModel | None: ...

    def get_secciones(self) -> list[SeccionModel]:...

    def create_seccion(self, seccion: SeccionModel) -> SeccionModel: ...

    def update_seccion(self, seccion_id: int, seccion: SeccionModel) -> SeccionModel | None: ...

    def delete_seccion(self, seccion_id: int) -> None: ...