from typing import Protocol
from ..models import SeccionModel

class SeccionPort(Protocol):
    async def get_seccion_by_id(self, seccion_id: int) -> SeccionModel | None: ...

    async def get_secciones(self) -> list[SeccionModel]:...

    async def create_seccion(self, seccion: SeccionModel) -> SeccionModel: ...

    async def update_seccion(self, seccion_id: int, seccion: SeccionModel) -> SeccionModel | None: ...

    async def delete_seccion(self, seccion_id: int) -> None: ...
