from typing import Protocol

from src.modules.catalogo.domain.models import TallaModel, ProductoTallaModel


class TallaPort(Protocol):
    async def get_all(self) -> list[TallaModel]: ...

    async def get_by_id(self, talla_id: int) -> TallaModel | None: ...

    async def create(self, model: TallaModel) -> TallaModel: ...

    async def update(self, talla_id: int, model: TallaModel) -> TallaModel | None: ...

    async def delete(self, talla_id: int) -> None: ...


class ProductoTallaPort(Protocol):
    async def get_all_by_producto(self, p_id: str) -> list[TallaModel]: ...

    async def get_by_id(self, p_talla_id: int) -> ProductoTallaModel: ...

    async def assign_to_producto(self, p_talla: ProductoTallaModel) -> ProductoTallaModel: ...

    async def remove_from_producto(self, producto_id: str,talla_id: int) -> None: ...
