from typing import Protocol

from src.modules.catalogo.domain.models import TallaModel, ProductoTallaModel


class TallaPort(Protocol):
    def get_all(self) -> list[TallaModel]: ...

    def get_by_id(self, talla_id: int) -> TallaModel | None: ...

    def create(self, model: TallaModel) -> TallaModel: ...

    def update(self, talla_id: int, model: TallaModel) -> TallaModel | None: ...

    def delete(self, talla_id: int) -> None: ...


class ProductoTallaPort(Protocol):
    def get_all_by_producto(self, p_id: str) -> list[TallaModel]: ...

    def get_by_id(self, p_talla_id: int) -> ProductoTallaModel: ...

    def assign_to_producto(self, p_talla: ProductoTallaModel) -> ProductoTallaModel: ...

    def remove_from_producto(self, producto_id: str,talla_id: int) -> None: ...
