from typing import Protocol, Optional, List
from src.modules.catalogo.domain.models import ProductoModel, ImagenModel, ProductoImagenModel

class ProductoPort(Protocol):
    def get_by_id(self, producto_id: str) -> Optional[ProductoModel]: ...

    def get_all(self) -> List[ProductoModel]: ...

    def get_by_categoria(self, categoria_id: int) -> List[ProductoModel]: ...

    def create_producto(self, producto: ProductoModel) -> ProductoModel: ...

    def update_producto(self, producto_id: str, producto: ProductoModel) -> ProductoModel: ...

    def delete_producto(self, producto_id: str) -> None: ...

class ImageStoragePort(Protocol):
    def upload(self, content: bytes, path: str) -> str: ...

    def delete(self, path: str) -> None: ...

class ImagePort(Protocol):
    def create(self, imagen: ImagenModel) -> ImagenModel: ...

    def get_by_id(self, imagen_id: int) -> ImagenModel | None: ...

    def delete(self, imagen_id: int) -> None: ...

class ProductImagePort(Protocol):
    def create(self, relation: ProductoImagenModel) -> ProductoImagenModel: ...

    def delete(self, producto_id: str, imagen_id: int) -> None: ...

    def get_by_producto(self, producto_id: str) -> list[ProductoImagenModel]: ...

    def delete_by_producto(self, producto_id: str) -> None: ...
