from src.modules.catalogo.domain.models import ProductoModel
from typing import Protocol, Optional, List

class ProductoPort(Protocol):
    def get_by_id(self, producto_id: str) -> Optional[ProductoModel]: ...

    def get_all(self) -> List[ProductoModel]: ...

    def get_by_categoria(self, categoria_id: int) -> List[ProductoModel]: ...

    def create_producto(self, producto: ProductoModel) -> ProductoModel: ...

    def update_producto(self, producto_id: str, producto: ProductoModel) -> ProductoModel: ...

    def delete_producto(self, producto_id: str) -> None: ...
