from src.modules.auth.domain.models import AuthUser, TokenPayload, RecoveryCode
from typing import Optional, Protocol, Mapping, Any


class AuthPort(Protocol):
    def create(self, user: AuthUser) -> AuthUser: ...
    def get_by_id(self, usuario_id: str) -> Optional[AuthUser]: ...
    def get_by_email(self, email: str) -> Optional[AuthUser]: ...
    def get_by_google_id(self, google_id: str) -> Optional[AuthUser]: ...
    def update_password(self, usuario_id: str, password_hash: str): ...
    def verify_user(self, usuario_id: str): ...
    def link_google(self, usuario_id: str, google_id: str) -> None: ...

class RecoveryCodePort(Protocol):
    def save(self, code: RecoveryCode) -> RecoveryCode: ...
    def get_by_user_id(self, user_id: str) -> Optional[RecoveryCode]: ...
    def delete_by_user_id(self, user_id: str) -> None: ...

class PasswordPort(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, plain: str, hash: str) -> bool: ...

class TokenPort(Protocol):
    def generate(self, payload: TokenPayload) -> str: ...
    def verify(self, token: str) -> TokenPayload: ...

class EmailPort(Protocol):
    def send_code(self, email: str, code: str): ...

class GoogleOAuthPort(Protocol):
    def build_auth_url(self) -> str: ...
    def exchange_code(self, code: str) -> Mapping[str, Any]: ...
    def verify_id_token(self, token: str) -> Mapping[str, Any]: ...